name: Docs

on:
  push:
    branches: [ main ]

jobs:
  mkdocs-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Set up uv
        uses: astral-sh/setup-uv@v6
      - run: uv sync --locked --group dev
      - run: uv run mkdocs gh-deploy --force
